%%-*- mode: erlang -*-
%%-*- coding: utf-8 -*-

% Test query options
[{tests, []}].

%% 
%% TESTS
%%

"WITH -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"WITH -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"WITH -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"WITH -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"WITH * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"WITH * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1".
"WITH * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"WITH * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1".
"WITH * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH * LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH * ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1".
"WITH + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"WITH + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"WITH 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".

"WITH DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"WITH DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT * WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"WITH DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"WITH DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"WITH DISTINCT * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"WITH DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT * LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT * ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"WITH DISTINCT 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1".
"WITH DISTINCT 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 WHERE nOt 'test_1' .property_1 :label_1 is null oR 'test_1' .property_1 :label_1 is null".
"WITH DISTINCT 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
