%%-*- mode: erlang -*-
%%-*- coding: utf-8 -*-

% Test query options
[{tests, []}].

%% 
%% TESTS
%%

"RETURN -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"RETURN -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN *".
"RETURN * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"RETURN * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"RETURN * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"RETURN * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1".
"RETURN * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN * ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"RETURN 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1".
"RETURN 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".

"RETURN DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"RETURN DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN DISTINCT -'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT *".
"RETURN DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN DISTINCT * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN DISTINCT * , + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"RETURN DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1".
"RETURN DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT * ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1".
"RETURN DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 AS variable_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
"RETURN DISTINCT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1 LIMIT + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"RETURN DISTINCT 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1".
"RETURN DISTINCT 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? AS variable_1 SKIP + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 contains 'test_2' .property_1 :label_1".
"RETURN DISTINCT 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ORDER BY - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ASC , 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? ASC".
