%%-*- mode: erlang -*-
%%-*- coding: utf-8 -*-

% Test query options
[{tests, []}].

%% 
%% TESTS
%%

"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1 = - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , variable_1 : node_1 : node_2".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 : node_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 : node_1 : node_2".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 : node_1 : node_2 , 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 += + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 - + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET 'Dies\" ist \"ein String' .Property_key_1 = - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , variable_1 : node_1 : node_2".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 : node_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 : node_1 : node_2".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 : node_1 : node_2 , 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 += + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 - + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".

"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1 = - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , variable_1 : node_1 : node_2".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 : node_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 : node_1 : node_2".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 : node_1 : node_2 , 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 += + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 - + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET variable_1 = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET 'Dies\" ist \"ein String' .Property_key_1 = - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4? , variable_1 : node_1 : node_2".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 : node_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 : node_1 : node_2".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 : node_1 : node_2 , 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 += + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 - + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON MATCH SET variable_1 = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 % + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1".

"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1 = - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ON CREATE SET variable_1 : node_1".
"MERGE ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ON MATCH SET variable_1 : node_1 : node_2 , 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1 = - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ON CREATE SET variable_1 : node_1".
"MERGE variable_1 = ALLSHORTESTPATHS ( ( variable_1 :node_1 { parameter_1 } ) <- [ variable_1 ?  : rel_type_1 | : rel_type_2 * 12 .. 34 { parameter_1 } ] -> ( variable_1 :node_1 { parameter_1 } ) ) ON CREATE SET 'Dies\" ist \"ein String' .Property_key_1? .Property_key_1! = + 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ^ - 'test_1' .property_1 :label_1 conTains 'test_2' .property_1 :label_1 ON MATCH SET variable_1 : node_1 : node_2 , 'Dies\" ist \"ein String' = 'test' .property_1 .property2? :label_1 :label_2 .property_3 .property4?".
