install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
language: erlang
otp_release:
  - 20.1
  - 19.3
  - 18.3
  - 17.5
script:
  - ./rebar3 compile
  - ./rebar3 eunit
  - ./rebar3 ct
